const PINNED_MESSAGE_DATE_FORMAT = 'YYYY-MM-DD';
const LOG_CHAT_ID = '-1001191278325';
const FIREBASE_DATE_FORMAT_WITH_UTC = 'YYYY-MM-DDTHH:mm:ssZZZZ';
const FIREBASE_DATE_FORMAT = 'YYYY-MM-DDTHH:mm:ss';
const MAX_DISPLAYED_COUNT = 5;

module.exports = {
  PINNED_MESSAGE_DATE_FORMAT,
  LOG_CHAT_ID,
  FIREBASE_DATE_FORMAT_WITH_UTC,
  FIREBASE_DATE_FORMAT,
  MAX_DISPLAYED_COUNT
};
