const FIREBASE_DATE_FORMAT = 'YYYY-MM-DDThh:mm:ss';
const PINNED_MESSAGE_DATE_FORMAT = 'YYYY-MM-DD';
const LOG_CHAT_ID = '-1001191278325';
const VADIMCPP_ID = '148045459';

module.exports = {
  FIREBASE_DATE_FORMAT,
  PINNED_MESSAGE_DATE_FORMAT,
  LOG_CHAT_ID,
  VADIMCPP_ID
};
